[env]
# Fix not being able to set font size (huge initial font):
WINIT_X11_SCALE_FACTOR = "1"

[window.padding]
x = 7

[font]
size = 10.5

    [font.normal]
    family = "Alt Hack Nerd Font"
    style =  "Regular"

    # Disable bold font:
    [font.bold]
    family = "Alt Hack Nerd Font"
    style =  "Regular"

[colors]
# Extra colors for specific purposes, colors 16-255 can be set:
indexed_colors = [
    { index = 16, color = "#d17c6b" },
    { index = 17, color = "#a3685a" },
    { index = 18, color = "#222525" },
    { index = 19, color = "#313438" },
    { index = 20, color = "#909090" },
    { index = 21, color = "#767676" },
    { index = 22, color = "#eaeaea" },
    { index = 23, color = "#404040" },
    { index = 24, color = "#6b6b6b" },
    { index = 25, color = "#656e6e" },
    { index = 26, color = "#2a2c2d" },
    { index = 27, color = "#797b7a" }
]

    [colors.cursor]
    cursor = "#d0d0d0"
    text =   "#0d0d0d"

    [colors.primary]
    background =     "#0d0d0d"
    foreground =     "#d0d0d0"
    dim_foreground = "#d0d0d0" # No such thing

    [colors.normal]
    black =   "#0d0d0d"
    red =     "#c36060"
    green =   "#a7bd68"
    yellow =  "#e8c580"
    blue =    "#7d9fbd"
    magenta = "#a684b0"
    cyan =    "#88bab0"
    white =   "#d0d0d0"

    [colors.bright]
    black =   "#5f6160" # Comment
    red =     "#c36060"
    green =   "#a7bd68"
    yellow =  "#e8c580"
    blue =    "#7d9fbd"
    magenta = "#a684b0"
    cyan =    "#88bab0"
    white =   "#ffffff" # Bright white exists but pretty much never used

    # Basically setting these to disallow using 'dim'
    #   https://en.wikipedia.org/wiki/ANSI_escape_code#SGR
    #
    # Otherwise alacritty calculates a darker version of normal color:
    #   https://alacritty.org/config-alacritty.html#s44
    [colors.dim]
    black =   "#5f6160"
    red =     "#c36060"
    green =   "#a7bd68"
    yellow =  "#e8c580"
    blue =    "#7d9fbd"
    magenta = "#a684b0"
    cyan =    "#88bab0"
    white =   "#d0d0d0"

    [colors.selection]
    text =       "#0d0d0d"
    background = "#d0d0d0"

    [colors.search]
    matches =       { foreground = "#0d0d0d", background = "#6b6b6b" }
    focused_match = { foreground = "#0d0d0d", background = "#d0d0d0" }

    [colors.footer_bar]
    foreground = "#d0d0d0"
    background = "#0d0d0d"
