env:
  # Fix not being able to set font size (huge initial font)
  WINIT_X11_SCALE_FACTOR: "1"

font:
  normal:
    family: Alt Hack Nerd Font
    style: Regular
  
  # Disable bold font:
  bold:
    family: Alt Hack Nerd Font
    style: Regular

  size: 12.5

window:
  padding:
    # Both left and right (unfortunately)
    x: 7

colors:
  primary:
    background: "#151515"
    foreground: "#d0d0d0"
 
  normal:
    black: "#151515"
    red: "#cc6666"
    green: "#a7bd68"
    yellow: "#f0c674"
    blue: "#81a2be"
    magenta: "#b294bb"
    cyan: "#8abeb7"
    white: "#d0d0d0"

  bright:
    black: "#5f6160"
    red: "#cd6a6a"
    green: "#a7bd68"
    yellow: "#f0c674"
    blue: "#81a2be"
    magenta: "#b294bb"
    cyan: "#8abeb7"
    white: "#ffffff"

  # Colors 16-255 can be set
  indexed_colors: [
    { index: 16, color: "#de935f" },
    { index: 17, color: "#a3685a" },
    { index: 18, color: "#222525" },
    { index: 19, color: "#313438" },
    { index: 20, color: "#909090" },
    { index: 21, color: "#eaeaea" },
    { index: 22, color: "#656e6e" },
    { index: 23, color: "#404040" },
    { index: 24, color: "#2a2c2d" },
    { index: 25, color: "#797b7a" }
  ]
