env:
  WINIT_X11_SCALE_FACTOR: "1"

font:
  normal:
    family: Roboto Mono
    style: Regular
  
  # Disable bold font:
  bold:
    family: Roboto Mono
    style: Regular

  size: 12.0

window:
  padding:
    x: 7

colors:
  primary:
    background: "#17191b"
    foreground: "#c5c8c6"
    
  normal:
    black: "#17191b"
    red: "#cc6666"
    green: "#b5bd68"
    yellow: "#f0c674"
    blue: "#81a2be"
    magenta: "#b294bb"
    cyan: "#8abeb7"
    white: "#c5c8c6"

  bright:
    black: "#5f6160"
    red: "#cc6666"
    green: "#b5bd68"
    yellow: "#f0c674"
    blue: "#81a2be"
    magenta: "#b294bb"
    cyan: "#8abeb7"
    white: "#ffffff"

  indexed_colors: [
    { index: 16, color: "#de935f" },
    { index: 17, color: "#a3685a" },
    { index: 18, color: "#1d1f21" },
    { index: 19, color: "#313438" },
    { index: 20, color: "#494e53" },
    { index: 21, color: "#e0e0e0" },
    { index: 22, color: "#383838" },
    { index: 23, color: "#202225" }
  ]
