#!/bin/bash

# Same appname and wmclass:
#     launch-or-focus <app>

# Different appname and wmclass:
#     launch-or-focus <app> <wmclass>

app="$1"
wmclass="${2:-$app}"

existing_id=$(xdotool search --onlyvisible --class "$wmclass" | tail -n 1)

if [ -z "$existing_id" ]; then
    "$app"
    exit 0
fi

active_window=$(xdotool getactivewindow)
active_class=$(xdotool getwindowclassname "$active_window")

if [ "$active_class" = "$wmclass" ]; then
    "$app"
    exit 0
fi

xdotool windowactivate "$existing_id"
