#!/usr/bin/env python3
# papis-short-help: Open a document's note and pdf in a combined action

import papis.api
import papis.cli
import click

@click.command()
@papis.cli.query_argument()
def main(query: str) -> None:
    documents = papis.api.get_documents_in_lib(
        papis.api.get_lib_name(),
        search=query
    )
    documents = papis.api.pick_doc(documents)

    from papis.commands.open import run as open_file
    from papis.commands.edit import edit_notes

    for document in documents:
        open_file(document)
        edit_notes(document)

if __name__ == "__main__":
	main()
