#!/bin/bash

# Change volume by n:
#       - can be negative to decrease
#       - or 0 to set volume at 0
n=$1

# Pavucontrol graphical slider caps at 153 (%)
# Cap at 150 here (a nice round number)
upper_limit=150

sink=0
current_volume=$(pactl get-sink-volume $sink | grep -Po '\d+(?=%)' | head -1)
new_volume=$((current_volume + n))

if [ "$1" == 0 ] || [ "$new_volume" -lt 0 ]; then
    new_volume=0
fi

if [ $new_volume -le $upper_limit ]; then
    pactl -- set-sink-volume $sink $new_volume%
else
    pactl -- set-sink-volume $sink $upper_limit%
    new_volume="$upper_limit"
fi

label="墳 $new_volume"

# If window is fullscreen, show notification because Polybar is not visible
fullscreen=$(xprop -id "$(xdo id)" _NET_WM_STATE | grep _NET_WM_STATE_FULLSCREEN)

if [ -n "$fullscreen" ]; then
    notify-send -t 700 \
                --hint=string:x-dunst-stack-tag:volume \
                "$label"
fi

# Update Polybar module with IPC
if [ "$new_volume" == 0 ]; then
    polybar-msg action volume send "%{F#808080}$label%{F-}"
else
    polybar-msg action volume send "$label"
fi
