#!/bin/bash

# Todo: doesn't reliably show on bar launch

sink=0
volume=$(pactl get-sink-volume $sink | grep -Po '\d+(?=%)' | head -1)

icon="墳"
if pactl list sinks | grep 'Active Port' | grep -q 'headphones' || \
   pactl list sinks short | grep -iq 'usb'; then
    icon="󰋋"
fi
label="$icon $volume"

if [ "$volume" == 0 ]; then
    echo "%{F#808080}$label%{F-}"
else
    echo "$label"
fi
