sort_by = "position"
separator_string = "󰧟"  # nf-md-circle_small

overflow_fg_color = "#e8c580"

[window_nicknames]
"TelegramDesktop"           = "telegram"
"firefox-developer-edition" = "firefox-dev"
"ardour-8.6.0"              = "ardour"
"gimp-2.10"                 = "gimp"
