sort_by = "position"
separator_string = "󰧟"

overflow_fg_color = "#e8c580"

[window_nicknames]
"TelegramDesktop"         = "telegram"
"firefoxdeveloperedition" = "firefox-dev"
"ardour-8.6.0"            = "ardour"
"gimp-2.10"               = "gimp"
