#!/bin/bash

# Kill duplicate instance
path_pid="/tmp/polybar-sand.pid"
if [ -f "$path_pid" ]; then
    pid=$(cat "$path_pid")
    if kill -0 "$pid" 2>/dev/null; then
        kill "$pid" &>/dev/null
    fi
fi
echo $$ > "$path_pid"

# Show timers (running, paused and elapsed) on the bar until none exist
# Todo: multiple timers
# Todo: click to pause/resume, right click to cancel
while true; do
    sand_ls=$(sand ls)
    if echo "$sand_ls" | grep -q "There are currently no timers."; then
        break
    fi

    polybar-msg action sand module_show

    second_line=$(echo "$sand_ls" | sed -n '2p')
    if echo "$second_line" | grep -q "Elapsed"; then
        label="%{F#e8c580} 00:00%{F-}"
    else
        # Show time in mm:ss, unless there are hours, hh:mm:ss
        # Todo: 3 or more digits hours are technically allowed
        hours_minutes_seconds=$(echo "$second_line" | sed -n 's/.*\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*/\1/p')
        hours=${hours_minutes_seconds%%:*}
        rest=${hours_minutes_seconds#*:}
        time_left=$rest
        if [ "$hours" != "00" ]; then
            time_left="$hours:$rest"
        fi

        if echo "$second_line" | grep -q "⏸"; then
            label="%{F#888888} $time_left%{F-}"
        elif [ "$time_left" = "00:00" ]; then
            label="%{F#e8c580} 00:00%{F-}"
        else
            label=" $time_left"
        fi
    fi

    polybar-msg action sand send "$label"
    sleep 1
done

# No timers
polybar-msg action sand module_hide
